version: 2
jobs:
  build:

    working_directory: ~/RestAssured

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      - restore_cache:

          key: RestAssured-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: RestAssured-{{ checksum "pom.xml" }}

      - run: mvn clean test

      - store_test_results:
          path: TestReport

      - store_artifacts:
          path: TestReport