version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
  - store_test_results:
      path: reports

      - store_artifacts:
          path: reports